# Uncomment the next line to define a global platform for your project
# platform :ios, '12.2'

target 'SemsterProject9' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SemsterProject9

 	pod 'Firebase'
 	pod 'Firebase/Core'
 	pod 'Firebase/Database'
 	pod 'Firebase/Auth' 

  target 'SemsterProject9Tests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'SemsterProject9UITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
